spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: password
  datasource:
    url: jdbc:postgresql://localhost:5432/expense_manager
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    name: expense_manager
  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#      format_sql: false
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
server:
  port: 8080
  servlet:
    context-path: /exmaServices
management:
  endpoints:
    web:
      base-path: /api/public/actuator